### PR TITLE
Fixed comparisons of F/W versions

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Fixed 2 bugs in the code that were incorrectly comparing versions between the currently installed F/W with the next F/W update available.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

FYI, I submitted a PR with the same fix to RMerlin's repository.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> FYI, I submitted a PR with the same fix to RMerlin's repository.

Great catch! Following for updates :)!

**Comment by Martinski4GitHub** [comment]
Just FYI,
RMerlin has already merged the equivalent PR into his "master" branch.
(Hopefully, Gnuton will do the same with this PR)

**Comment by gnuton** [comment]
Thanks @Martinski4GitHub !

**Pull request merged**
