### PR TITLE
Dsl feature repeater v386 stable

### PR DESCRIPTION
**Pull request by andreabellitto**
I have added the Wi-Fi repeater support to the 386.02 mainline. I already have tested the compilation and I also have flashed and tested the compiled image on my DSL-AC68U. All seems to be working as it should.

### CODE REVIEW

**Comment by gnuton** [comment]
Merging to separate feature branch for testing.
Thanks a lot! 
I will give you feedback as soon as I test it more properly.

**Comment by andreabellitto** [comment]
Just only one thing regarding the branch's name, gnuton:DEV_REPEATER_ABELLITO, my surname is BELLI**TT**O  ;)

**Comment by gnuton** [comment]
Ciao Andrea,
Thanks for rebasing the changes on top the latest master.
I branched it and merged the changes into the DEV_REPEATER_ABELLITO.
That branch is currently based on 386.2-beta2.

CI has built the firmware and this is the image containing the repeater feature from your branch.
https://1039-175516287-gh.circle-artifacts.com/0/workspace/release/DSL-AC68U_386.2_beta2_DSL_1.0.5.3.trx

I do have tested still really little, but the Wizard was not working, not sure yet why.
the cfe.o is not present in DSL-AC68U GPLs. is that from RT?
DSL-AX82U have the cfe.o although.
Do you have plans to integrate this more so that wizard and WAN would work for both DSL and RT mode?
in the main page also the operational mode is missing at the top (please see picture)
image

**Comment by andreabellitto** [comment]
About the wizard it is not working in the left panel because it does't currently take care of the getJsonFromUrl["flag"] parameter and so  the QIS wizard doen't recognize the current operatio mode of the device, I will take a better look at that and maybe I will fix it.

Yes, the cfe.o is the one from RT, I took it from your old archived branch.

As I said I hope to have some free time one of the following evenings so I can fix the wizard for both DSL and RT mdoe.

I did't know about the top "operation mode" label, maybe I will take a look at that too, anyway you can find the current operation mode setting in the Administration left menu.

**Comment by andreabellitto** [comment]
Please see https://github.com/gnuton/asuswrt-merlin.ng/pull/94 for the following fixes:

- Wizard is not working
- Missing operation mode in top status bar

**Pull request merged**
